import { useEffect, useRef } from "react";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

interface ShortcutHandlers {
  onSave?: () => void;
  onFind?: () => void;
  onReplace?: () => void;
  onGotoLine?: () => void;
  onNewFile?: () => void;
  onOpenFile?: () => void;
  onCloseTab?: () => void;
  onFindInFiles?: () => void;
  onToggleBookmark?: () => void;
  onNextBookmark?: () => void;
  onToggleMacro?: () => void;
  onPlayMacro?: () => void;
  onToggleDiff?: () => void;
  onEncoding?: () => void;
  onSettings?: () => void;
  onCopy?: () => void;
  onPaste?: () => void;
  onCut?: () => void;
  onToggleSidebar?: () => void;
  onCommandPalette?: () => void;
  onShortcutsHelp?: () => void;
  onEditAction?: (action: string) => void;
  onSplitHorizontal?: () => void;
  onSplitVertical?: () => void;
  onSplitClose?: () => void;
  onFunctionList?: () => void;
  onToggleWordWrap?: () => void;
  onToggleRuler?: () => void;
  onCharStats?: () => void;
  onHexViewer?: () => void;
  onMultiDocSearch?: () => void;
  onTextTransform?: () => void;
  onInsertDateTime?: () => void;
  onSpecialChar?: () => void;
  onColorPicker?: () => void;
  onDocSwitcher?: () => void;
  onBatchFindReplace?: () => void;
  onFileProps?: () => void;
  onShortcutMapper?: () => void;
  onEolConvert?: (target: "lf" | "crlf" | "cr") => void;
  onTabSpaceConvert?: (direction: "tab-to-space" | "space-to-tab") => void;
  onFormatCode?: () => void;
  onMarkdownPreview?: () => void;
  onRegexTester?: () => void;
  onCsvViewer?: () => void;
  onLanguageSelector?: () => void;
  onZoomIn?: () => void;
  onZoomOut?: () => void;
  onZoomReset?: () => void;
  onFindNext?: () => void;
  onFindPrev?: () => void;
  onPrevBookmark?: () => void;
  onClearBookmarks?: () => void;
  onJumpToBracket?: () => void;
  onSelectToBracket?: () => void;
  onCopyPath?: () => void;
  onReloadFromDisk?: () => void;
  onInsertFile?: () => void;
  onFullScreen?: () => void;
  onAlwaysOnTop?: () => void;
  onFormatJson?: () => void;
  onFormatXml?: () => void;
  onFormatHtml?: () => void;
  onFormatCss?: () => void;
  onFormatSql?: () => void;
  onCharConvert?: (action: string) => void;
  onSaveCopy?: () => void;
  onOpenWithEncoding?: () => void;
  onToggleBom?: () => void;
  onSaveAll?: () => void;
  onCopyDirectory?: () => void;
  onCopyFileName?: () => void;
  onClipboardHistory?: () => void;
  onSnippets?: () => void;
  onPluginManager?: () => void;
  onRunCommand?: () => void;
  onOpenInDefault?: () => void;
  onRunMacroMultiple?: () => void;
  onPostItMode?: () => void;
  onSentenceCase?: () => void;
  onRandomCase?: () => void;
  onSaveAs?: () => void;
  onCloseAll?: () => void;
  onCloseAllButCurrent?: () => void;
  onQuit?: () => void;
  onMarkAll?: () => void;
  onUnmarkAll?: () => void;
  onEncodeWith?: (encoding: string) => void;
  onConvertEncoding?: (encoding: string) => void;
  onMacroStartStop?: () => void;
  onMacroPlayback?: () => void;
  onMacroSave?: () => void;
  onAbout?: () => void;
  onSetLanguage?: (lang: string) => void;
  onCompareStart?: () => void;
  onCompareClear?: () => void;
  onCompareSyncScroll?: () => void;
  onCompareNextDiff?: () => void;
  onComparePrevDiff?: () => void;
  onWindowSort?: (by: "name" | "path" | "time") => void;
  onWindowCascade?: () => void;
  onWindowTileHorizontal?: () => void;
  onWindowTileVertical?: () => void;
  onWindowList?: () => void;
}

export function useKeyboardShortcuts(handlers: ShortcutHandlers): void {
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;

  useEffect(() => {
    let unlisten: UnlistenFn | null = null;
    let active = true;

    (async () => {
      unlisten = await listen<string>("menu-event", (event) => {
        const id = event.payload;
        const h = handlersRef.current;
        switch (id) {
          case "save": h.onSave?.(); break;
          case "find": h.onFind?.(); break;
          case "replace": h.onReplace?.(); break;
          case "goto": h.onGotoLine?.(); break;
          case "new": h.onNewFile?.(); break;
          case "open": h.onOpenFile?.(); break;
          case "close": h.onCloseTab?.(); break;
          case "find_in_files": h.onFindInFiles?.(); break;
          case "encoding": h.onEncoding?.(); break;
          case "settings": h.onSettings?.(); break;
          case "toggle_sidebar": h.onToggleSidebar?.(); break;
          case "command_palette": h.onCommandPalette?.(); break;
          case "shortcuts": h.onShortcutsHelp?.(); break;
          case "edit_delete_line": h.onEditAction?.("delete-line"); break;
          case "edit_duplicate_line": h.onEditAction?.("duplicate-line"); break;
          case "edit_move_up": h.onEditAction?.("move-up"); break;
          case "edit_move_down": h.onEditAction?.("move-down"); break;
          case "edit_delete_blank": h.onEditAction?.("delete-blank"); break;
          case "edit_trim_trailing": h.onEditAction?.("trim-trailing"); break;
          case "edit_toggle_comment": h.onEditAction?.("toggle-comment"); break;
          case "edit_upper": h.onEditAction?.("upper"); break;
          case "edit_lower": h.onEditAction?.("lower"); break;
          case "edit_sort_asc": h.onEditAction?.("sort-asc"); break;
          case "edit_sort_desc": h.onEditAction?.("sort-desc"); break;
          case "edit_sort_length_asc": h.onEditAction?.("sort-length-asc"); break;
          case "edit_sort_length_desc": h.onEditAction?.("sort-length-desc"); break;
          case "edit_sort_random": h.onEditAction?.("sort-random"); break;
          case "edit_reverse_lines": h.onEditAction?.("reverse-lines"); break;
          case "edit_filter_lines": h.onEditAction?.("filter-lines"); break;
          case "edit_filter_lines_remove": h.onEditAction?.("filter-lines-remove"); break;
          case "edit_merge_lines": h.onEditAction?.("merge-lines"); break;
          case "edit_merge_lines_comma": h.onEditAction?.("merge-lines-comma"); break;
          case "edit_split_line": h.onEditAction?.("split-line"); break;
          case "edit_insert_blank_above": h.onEditAction?.("insert-blank-above"); break;
          case "edit_insert_blank_below": h.onEditAction?.("insert-blank-below"); break;
          case "edit_keep_blank_only": h.onEditAction?.("keep-blank-only"); break;
          case "edit_remove_adj_dup": h.onEditAction?.("remove-adj-dup"); break;
          case "edit_split_by_comma": h.onEditAction?.("split-by-comma"); break;
          case "edit_remove_dup": h.onEditAction?.("remove-duplicates"); break;
          case "edit_undo": h.onEditAction?.("undo"); break;
          case "edit_redo": h.onEditAction?.("redo"); break;
          case "edit_copy": h.onCopy?.(); break;
          case "edit_paste": h.onPaste?.(); break;
          case "edit_cut": h.onCut?.(); break;
          case "split_horizontal": h.onSplitHorizontal?.(); break;
          case "split_vertical": h.onSplitVertical?.(); break;
          case "split_close": h.onSplitClose?.(); break;
          case "function_list": h.onFunctionList?.(); break;
          case "toggle_word_wrap": h.onToggleWordWrap?.(); break;
          case "toggle_ruler": h.onToggleRuler?.(); break;
          case "char_stats": h.onCharStats?.(); break;
          case "hex_viewer": h.onHexViewer?.(); break;
          case "multi_search": h.onMultiDocSearch?.(); break;
          case "text_transform": h.onTextTransform?.(); break;
          case "insert_datetime": h.onInsertDateTime?.(); break;
          case "special_char": h.onSpecialChar?.(); break;
          case "color_picker": h.onColorPicker?.(); break;
          case "doc_switcher": h.onDocSwitcher?.(); break;
          case "batch_find_replace": h.onBatchFindReplace?.(); break;
          case "file_props": h.onFileProps?.(); break;
          case "shortcut_mapper": h.onShortcutMapper?.(); break;
          case "eol_lf": h.onEolConvert?.("lf"); break;
          case "eol_crlf": h.onEolConvert?.("crlf"); break;
          case "eol_cr": h.onEolConvert?.("cr"); break;
          case "tab_to_space": h.onTabSpaceConvert?.("tab-to-space"); break;
          case "space_to_tab": h.onTabSpaceConvert?.("space-to-tab"); break;
          case "format_code": h.onFormatCode?.(); break;
          case "markdown_preview": h.onMarkdownPreview?.(); break;
          case "regex_tester": h.onRegexTester?.(); break;
          case "csv_viewer": h.onCsvViewer?.(); break;
          case "language_selector": h.onLanguageSelector?.(); break;
          case "zoom_in": h.onZoomIn?.(); break;
          case "zoom_out": h.onZoomOut?.(); break;
          case "zoom_reset": h.onZoomReset?.(); break;
          case "find_next": h.onFindNext?.(); break;
          case "find_prev": h.onFindPrev?.(); break;
          case "next_bookmark": h.onNextBookmark?.(); break;
          case "prev_bookmark": h.onPrevBookmark?.(); break;
          case "clear_bookmarks": h.onClearBookmarks?.(); break;
          case "jump_to_bracket": h.onJumpToBracket?.(); break;
          case "select_to_bracket": h.onSelectToBracket?.(); break;
          case "copy_path": h.onCopyPath?.(); break;
          case "reload_from_disk": h.onReloadFromDisk?.(); break;
          case "insert_file": h.onInsertFile?.(); break;
          case "full_screen": h.onFullScreen?.(); break;
          case "always_on_top": h.onAlwaysOnTop?.(); break;
          case "format_json": h.onFormatJson?.(); break;
          case "format_xml": h.onFormatXml?.(); break;
          case "format_html": h.onFormatHtml?.(); break;
          case "format_css": h.onFormatCss?.(); break;
          case "format_sql": h.onFormatSql?.(); break;
          case "char_full_width": h.onCharConvert?.("to-full-width"); break;
          case "char_half_width": h.onCharConvert?.("to-half-width"); break;
          case "char_remove_non_printable": h.onCharConvert?.("remove-non-printable"); break;
          case "char_normalize_nfc": h.onCharConvert?.("normalize-nfc"); break;
          case "char_normalize_nfd": h.onCharConvert?.("normalize-nfd"); break;
          case "char_to_snake": h.onCharConvert?.("to-snake"); break;
          case "char_to_camel": h.onCharConvert?.("to-camel"); break;
          case "char_to_pascal": h.onCharConvert?.("to-pascal"); break;
          case "char_to_kebab": h.onCharConvert?.("to-kebab"); break;
          case "save_copy": h.onSaveCopy?.(); break;
          case "open_with_encoding": h.onOpenWithEncoding?.(); break;
          case "toggle_bom": h.onToggleBom?.(); break;
          case "save_all": h.onSaveAll?.(); break;
          case "copy_directory": h.onCopyDirectory?.(); break;
          case "copy_filename": h.onCopyFileName?.(); break;
          case "clipboard_history": h.onClipboardHistory?.(); break;
          case "snippets": h.onSnippets?.(); break;
          case "plugin_manager": h.onPluginManager?.(); break;
          case "run_command": h.onRunCommand?.(); break;
          case "open_in_default": h.onOpenInDefault?.(); break;
          case "run_macro_multiple": h.onRunMacroMultiple?.(); break;
          case "postit_mode": h.onPostItMode?.(); break;
          case "edit_sentence_case": h.onSentenceCase?.(); break;
          case "edit_random_case": h.onRandomCase?.(); break;
          case "save_as": h.onSaveAs?.(); break;
          case "close_all": h.onCloseAll?.(); break;
          case "close_all_but_current": h.onCloseAllButCurrent?.(); break;
          case "quit": h.onQuit?.(); break;
          case "mark_all": h.onMarkAll?.(); break;
          case "unmark_all": h.onUnmarkAll?.(); break;
          case "encode_utf8": h.onEncodeWith?.("UTF-8"); break;
          case "encode_utf8_bom": h.onEncodeWith?.("UTF-8-BOM"); break;
          case "encode_gbk": h.onEncodeWith?.("GBK"); break;
          case "encode_gb2312": h.onEncodeWith?.("GB2312"); break;
          case "encode_utf16le": h.onEncodeWith?.("UTF-16LE"); break;
          case "encode_utf16be": h.onEncodeWith?.("UTF-16BE"); break;
          case "encode_ascii": h.onEncodeWith?.("ASCII"); break;
          case "encode_big5": h.onEncodeWith?.("Big5"); break;
          case "encode_shiftjis": h.onEncodeWith?.("Shift-JIS"); break;
          case "encode_euckr": h.onEncodeWith?.("EUC-KR"); break;
          case "encode_iso88591": h.onEncodeWith?.("ISO-8859-1"); break;
          case "encode_windows1252": h.onEncodeWith?.("Windows-1252"); break;
          case "convert_utf8": h.onConvertEncoding?.("UTF-8"); break;
          case "convert_utf8_bom": h.onConvertEncoding?.("UTF-8-BOM"); break;
          case "convert_gbk": h.onConvertEncoding?.("GBK"); break;
          case "convert_gb2312": h.onConvertEncoding?.("GB2312"); break;
          case "convert_utf16le": h.onConvertEncoding?.("UTF-16LE"); break;
          case "convert_utf16be": h.onConvertEncoding?.("UTF-16BE"); break;
          case "convert_big5": h.onConvertEncoding?.("Big5"); break;
          case "convert_shiftjis": h.onConvertEncoding?.("Shift-JIS"); break;
          case "convert_euckr": h.onConvertEncoding?.("EUC-KR"); break;
          case "convert_iso88591": h.onConvertEncoding?.("ISO-8859-1"); break;
          case "convert_windows1252": h.onConvertEncoding?.("Windows-1252"); break;
          case "macro_start_stop": h.onMacroStartStop?.(); break;
          case "macro_playback": h.onMacroPlayback?.(); break;
          case "macro_save": h.onMacroSave?.(); break;
          case "about": h.onAbout?.(); break;
          case "lang_plaintext": h.onSetLanguage?.("plaintext"); break;
          case "lang_javascript": h.onSetLanguage?.("javascript"); break;
          case "lang_typescript": h.onSetLanguage?.("typescript"); break;
          case "lang_python": h.onSetLanguage?.("python"); break;
          case "lang_rust": h.onSetLanguage?.("rust"); break;
          case "lang_c": h.onSetLanguage?.("c"); break;
          case "lang_cpp": h.onSetLanguage?.("cpp"); break;
          case "lang_java": h.onSetLanguage?.("java"); break;
          case "lang_go": h.onSetLanguage?.("go"); break;
          case "lang_html": h.onSetLanguage?.("html"); break;
          case "lang_css": h.onSetLanguage?.("css"); break;
          case "lang_json": h.onSetLanguage?.("json"); break;
          case "lang_xml": h.onSetLanguage?.("xml"); break;
          case "lang_markdown": h.onSetLanguage?.("markdown"); break;
          case "lang_sql": h.onSetLanguage?.("sql"); break;
          case "lang_shell": h.onSetLanguage?.("shell"); break;
          case "lang_yaml": h.onSetLanguage?.("yaml"); break;
          case "compare_start": h.onCompareStart?.(); break;
          case "compare_clear": h.onCompareClear?.(); break;
          case "compare_sync_scroll": h.onCompareSyncScroll?.(); break;
          case "compare_next_diff": h.onCompareNextDiff?.(); break;
          case "compare_prev_diff": h.onComparePrevDiff?.(); break;
          case "window_sort_name": h.onWindowSort?.("name"); break;
          case "window_sort_path": h.onWindowSort?.("path"); break;
          case "window_sort_time": h.onWindowSort?.("time"); break;
          case "window_cascade": h.onWindowCascade?.(); break;
          case "window_tile_horizontal": h.onWindowTileHorizontal?.(); break;
          case "window_tile_vertical": h.onWindowTileVertical?.(); break;
          case "window_list": h.onWindowList?.(); break;
        }
      });
      if (!active) { unlisten(); unlisten = null; }
    })();

    const handleCustomEvent = (e: Event) => {
      const type = (e as CustomEvent).type;
      const h = handlersRef.current;
      switch (type) {
        case "markpt:save": h.onSave?.(); break;
        case "markpt:find": h.onFind?.(); break;
        case "markpt:replace": h.onReplace?.(); break;
        case "markpt:goto-line": h.onGotoLine?.(); break;
        case "markpt:new-file": h.onNewFile?.(); break;
        case "markpt:open-file": h.onOpenFile?.(); break;
        case "markpt:close-tab": h.onCloseTab?.(); break;
        case "markpt:find-in-files": h.onFindInFiles?.(); break;
        case "markpt:toggle-bookmark": h.onToggleBookmark?.(); break;
        case "markpt:next-bookmark": h.onNextBookmark?.(); break;
        case "markpt:toggle-macro": h.onToggleMacro?.(); break;
        case "markpt:play-macro": h.onPlayMacro?.(); break;
        case "markpt:toggle-diff": h.onToggleDiff?.(); break;
        case "markpt:encoding": h.onEncoding?.(); break;
        case "markpt:settings": h.onSettings?.(); break;
      }
    };

    const events = [
      "markpt:save", "markpt:find", "markpt:replace", "markpt:goto-line",
      "markpt:new-file", "markpt:open-file", "markpt:close-tab",
      "markpt:find-in-files", "markpt:toggle-bookmark", "markpt:next-bookmark",
      "markpt:toggle-macro", "markpt:play-macro", "markpt:toggle-diff",
      "markpt:encoding", "markpt:settings",
    ];

    events.forEach((evt) => window.addEventListener(evt, handleCustomEvent));

    return () => {
      active = false;
      if (unlisten) unlisten();
      events.forEach((evt) => window.removeEventListener(evt, handleCustomEvent));
    };
  }, []);
}
